### ISSUE TITLE
Can't retrieve metrics due to getRandomValues ArrayBufferView length error

### ISSUE THREAD

**Issue by dborkan** [willscott/freedomjs-anonymized-metrics#12]
Seen using both freedomjs-anonymized-metrics v0.7.0 and v0.6.0 in a Chrome App (uProxy).  After making our call to retrieve, I see an exception inside the refreshBuffer function in crypto.ts, on https://github.com/willscott/freedomjs-anonymized-metrics/blob/master/src/crypto.js#L17

Because of Freedom error handling, the error printed to the console is just `Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': An object could not be cloned.(…)`, however if I try making a call to `crypto.getRandomValues(buf)` at this point I see the error `Uncaught DOMException: Failed to execute 'getRandomValues' on 'Crypto': The ArrayBufferView's byte length (98305) exceeds the number of bytes of entropy available via this API (65536)`

I can easily replicate this in uProxy by forcing uProxy to generate metrics more frequently (every 5 seconds as opposed to every day), but I will try to create a simpler test project.

**Comment by mollyling** [comment]
Ref: https://github.com/willscott/freedomjs-anonymized-metrics/pull/9

**Comment by mollyling** [comment]
There are two parts to this:
(1) The API acts horribly when it runs out of pre-calc'd random values.  It should warn and just get more random values;
(2) The API doesn't precalculate enough random values.  This, I suspect, is harder than originally believed, so I'd prefer to have its failure be a sub-optimal code path instead of a hard failure.

I'll work on this.

**Comment by willscott** [comment]
I started trying to look at what's happening here:

We try to follow the same design as the original rappor implementation
which uses a deterministic set of randomness. they do it with a seeded
random generator, and that seems 'bad' - because the only JS way to do that
would be to use a mersene twister or some similar deterministic algorithm
and implement it fully in javascript.
Instead, we take real randomness and 'memoize' it - we save the state and
'replay' it when we need to show the same deterministic values.

In the getRandomInteger case, which is used by rappor to slot the client
into a cohort, and comes from a call to math.Random() rather than a
cryptographically secure call, this ends up happening here:
https://github.com/willscott/rappor/blob/master/rappor.js#L66

We make the random object here:
https://github.com/willscott/freedomjs-anonymized-metrics/blob/master/src/metric.js#L61

We basically save the state to disk and restore (e.g.)
https://github.com/willscott/freedomjs-anonymized-metrics/blob/master/src/metric.js#L112

2 things we need to look at:
1. does it do a correct round-trip
2. are we restoring when a different set of rappor parameters is being
used? if so, the call order will be different, and we'll end up getting
'out of order' on our restoration. If we ever have the consuming call fail
as lally noticed in
https://github.com/willscott/rappor/blob/master/rappor.js#L285
that means that we're 'off' in our randomness and values won't be correct
at all.  That seems like the place to start investigating.

**Comment by willscott** [comment]
v0.7.3 allocates more randomness. lets close for now, and re-open if new issues emerge.
